export const SETTING_LIBRARY = "SETTING_LIBRARY";
export const SET_LIBRARY_SUCCESS = "SET_LIBRARY_SUCCESS";
export const SET_LIBRARY_FAIL = "SET_LIBRARY_FAIL";

export const SETTING_PATIENT = "SETTING_PATIENT";
export const SET_PATIENT_SUCCESS = "SET_PATIENT_SUCCESS";
export const SET_PATIENT_FAIL = "SET_PATIENT_FAIL";

export const SETTING_SMART = "SETTING_SMART";
export const SET_SMART_SUCCESS = "SET_SMART_SUCCESS";
export const SET_SMART_FAIL = "SET_SMART_FAIL";

export const SET_SELECTIONS = "SET_SELECTIONS";
export const REMOVE_SELECTION = "REMOVE_SELECTION";
export const ADD_SELECTION = "ADD_SELECTION";

export const SETTING_RESULTS = "SETTING_RESULTS";
export const SET_RESULTS_SUCCESS = "SET_RESULTS_SUCCESS";
export const SET_RESULTS_FAIL = "SET_RESULTS_FAIL";
